sudo: required

services:
    - docker

script:
    - export VERSION=$(git describe --tags)
    - sed -i "s/CAPTAIN_VERSION/${VERSION}/" main.go
    - make build

deploy:
    provider: releases
    api_key: $GITHUB_TOKEN
    file_glob: true
    file: dist/*
    on:
        tags: true
